apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: umami
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /umami-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: umami
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
