apiVersion: v1
kind: Secret
metadata:
  name: umami-config
  namespace: umami
type: Opaque
stringData:
  pg-password: umami
  database-url: "postgresql://umami:umami@postgres:5432/umami"
  hash-salt: RANDOM-STRING
